"""Initial migration

Revision ID: a1f38d5ac941
Revises: 
Create Date: 2023-12-12 10:32:02.542897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1f38d5ac941'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fantasy_rosters')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')

    op.drop_table('users')
    op.drop_table('fantasy_teams')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('home_team_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('away_team_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'teams', ['home_team_id'], ['team_id'])
        batch_op.create_foreign_key(None, 'teams', ['away_team_id'], ['team_id'])

    with op.batch_alter_table('passing_game_logs', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('player_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['game_id'])
        batch_op.create_foreign_key(None, 'players', ['player_id'], ['player_id'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['team_id'])

    with op.batch_alter_table('receiving_game_logs', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('player_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['game_id'])
        batch_op.create_foreign_key(None, 'players', ['player_id'], ['player_id'])

    with op.batch_alter_table('rushing_game_logs', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('player_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['game_id'])
        batch_op.create_foreign_key(None, 'players', ['player_id'], ['player_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rushing_game_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('player_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('game_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('receiving_game_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('player_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('game_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('passing_game_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('player_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('game_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('away_team_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('home_team_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('fantasy_teams',
    sa.Column('fantasy_team_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('season', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('logo_image_url', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('fantasy_team_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.create_index('email', ['email'], unique=False)

    op.create_table('fantasy_rosters',
    sa.Column('fantasy_team_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('fantasy_team_id', 'player_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
