"""Add active field to players table

Revision ID: a8610b0c9809
Revises: a1f38d5ac941
Create Date: 2023-12-12 11:01:33.188636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8610b0c9809"
down_revision = "a1f38d5ac941"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("active", sa.Boolean(), nullable=False, server_default="1")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_column("active")

    # ### end Alembic commands ###
