"""Add team_id to game logs

Revision ID: acef69d22497
Revises: a8610b0c9809
Create Date: 2023-12-12 11:22:41.545439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = "acef69d22497"
down_revision = "a8610b0c9809"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("passing_game_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("team_id", sa.Integer(), nullable=False))

    with op.batch_alter_table("passing_game_logs", schema=None) as batch_op:
        connection = op.get_bind()
        connection.execute(
            text(
                "UPDATE passing_game_logs pg SET pg.team_id = (SELECT p.team_id FROM players p WHERE p.player_id = pg.player_id)"
            )
        )

    # add foreign key relationship
    with op.batch_alter_table("passing_game_logs", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "teams", ["team_id"], ["team_id"])

    with op.batch_alter_table("receiving_game_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("team_id", sa.Integer(), nullable=False))

    with op.batch_alter_table("passing_game_logs", schema=None) as batch_op:
        # Set team_id for ReceivingGameLog
        connection = op.get_bind()
        connection.execute(
            text(
                "UPDATE receiving_game_logs rg SET rg.team_id = (SELECT p.team_id FROM players p WHERE p.player_id = rg.player_id)"
            )
        )

    with op.batch_alter_table("receiving_game_logs", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "teams", ["team_id"], ["team_id"])

    with op.batch_alter_table("rushing_game_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("team_id", sa.Integer(), nullable=False))

    with op.batch_alter_table("rushing_game_logs", schema=None) as batch_op:
        # Set team_id for RushingGameLog
        connection = op.get_bind()
        connection.execute(
            text(
                "UPDATE rushing_game_logs rg SET rg.team_id = (SELECT p.team_id FROM players p WHERE p.player_id = rg.player_id)"
            )
        )

    with op.batch_alter_table("rushing_game_logs", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "teams", ["team_id"], ["team_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rushing_game_logs", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("team_id")

    with op.batch_alter_table("receiving_game_logs", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("team_id")

    with op.batch_alter_table("passing_game_logs", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("team_id")

    # ### end Alembic commands ###
